export const fields = [
    { name: "ipAddress", label: "IP Address", type: "text", value: "", required: true },
    { name: "period", label: "Period (seconds)", type: "number", value: "", required: true },
    {
      name: "timePeriod",
      label: "Time Period",
      type: "select",
      required: true,
      options: [
        { value: "5m", label: "5 Minutes" },
        { value: "10m", label: "10 Minutes" },
        { value: "15m", label: "15 Minutes" },
        { value: "30m", label: "30 Minutes" },
        { value: "1h", label: "Last Hour" },
        { value: "2h", label: "Last 2 Hours" },
        { value: "3h", label: "Last 3 Hours" },
        { value: "4h", label: "Last 4 Hours" },
        { value: "5h", label: "Last 5 Hours" },
        { value: "6h", label: "Last 6 Hours" },
        { value: "8h", label: "Last 8 Hours" },
        { value: "12h", label: "Last 12 Hours" },
        { value: "1d", label: "Last Day" },
        { value: "2d", label: "Last 2 Days" },
        { value: "3d", label: "Last 3 Days" },
        { value: "4d", label: "Last 4 Days" },
        { value: "5d", label: "Last 5 Days" },
        { value: "6d", label: "Last 6 Days" },
        { value: "1w", label: "Last 1 Week" },
        { value: "2w", label: "Last 2 Weeks" },
        { value: "3w", label: "Last 3 Weeks" },
        { value: "4w", label: "Last 4 Weeks" },
      ],
      value: "",
    },
  ];